### ISSUE TITLE
Description of protocol

### ISSUE THREAD

**Issue by nathanvdh** [ozczecho/vzduch-dotek#10]
Hi Mike,

I'm looking at writing something for interacting with my AirTouch2. I've been looking at your code and I'm curious about the protocol as I think the command messages you are sending for AT3 are identical to my AT2 ones. Would you be able to describe the protocol a little more in detail to me?
E.g. byte 1/13 is clearly a header, byte 2/13 seems to identify whether it is a command for the whole AC or for a specific zone (but then its diffferent for the setTime and setName commands), strangely byte 3 is identical for all commands - do you know what this represents? Byte 4 seems to be the target (acID or roomID), finally byte 5 is even more of a mystery, initially I thought it was just part of the payload/data but it seems to be common between some commands - ToggleAcOnOff, ToggleZone and SetChangeTemperatureFan. Any help and info is greatly appreciated. Thanks.

**Comment by ozczecho** [comment]
Hi @nathanvdh - Sorry for late reply - I have been away.

I don't have any documentation on the protocol. I basically reverse engineered their apk file along with some help checking forums / github (example: https://community.openhab.org/t/polyaire-airtouch-2-a-c-controller/19692/25) & https://github.com/mihailescu2m/homebridge-airtouch4-platform.

Now there is also https://github.com/tonymyatt/airtouch3api -   based off my work but written in python and with explanations https://github.com/tonymyatt/airtouch3api/blob/main/airtouch3/constants.py - maybe that can help you?

I don't know how similar AT2 v AT3 - but AT4 was totally different.

Good luck.

**Comment by describe19** [comment]
Thanks for the pointers, really appreciate it!

**Comment by nathanvdh** [comment]
> Hi @nathanvdh - Sorry for late reply - I have been away.
> 
> I don't have any documentation on the protocol. I basically reverse engineered their apk file along with some help checking forums / github (example: https://community.openhab.org/t/polyaire-airtouch-2-a-c-controller/19692/25) & https://github.com/mihailescu2m/homebridge-airtouch4-platform.
> 
> Now there is also https://github.com/tonymyatt/airtouch3api - based off my work but written in python and with explanations https://github.com/tonymyatt/airtouch3api/blob/main/airtouch3/constants.py - maybe that can help you?
> 
> I don't know how similar AT2 v AT3 - but AT4 was totally different.
> 
> Good luck.

Thanks for the pointers, really appreciate it!
