### ISSUE TITLE
Zone-based temperature control

### ISSUE THREAD

**Issue by L0rdCha0s** [ozczecho/vzduch-dotek#2]
Hi there!

Firstly - amazing reverse engineering effort.  My congratulations.

Secondly - any idea what part of the protocol handles the zone-based temperature setting (as opposed to the current 'SetNewTemperature' function which looks like it sets the 'SetPoint' in the AirTouch app?  (Unsure what SetPoint actually is anyway)

**Comment by ozczecho** [comment]
Hi @L0rdCha0s  - apologies for the delayed response.

I believe what you want is the `SetFan` function. In the AT3 app you can set the zones temp or the % of the damper. 

In our setup we have the AT3 unit plus I bought one of those temperature pucks from Polyaire. The puck is used to control the temperature in our living area zone. The `SetPoint` is the desired temperature. I have the aircon using the puck as the source of the temperature. And I control the setpoint via this api.

The other 4 zones I have the dampers set at 100% and use my own temperature sensors to measure the temperature. I use Home Assistant plus this API to switch each zone  ON / OFF based on the zones desired temp.

Anyway hope this helps. Let me know if that worked. If not I can dig and experiment a little more next weekend.

**Comment by L0rdCha0s** [comment]
Ah, perfect, will have an experiment here

I have four zones and four of the pucks - each zone current temperature is reading fine, so I’ll see if the setFan function works

Thanks again!

**Comment by tidalvirus** [comment]
Hi @L0rdCha0s - before I dig too deep - did you already figure out how to read and set the temps for the other zones? I've got 6 zones / 6 sensors, and it would be nice to adjust that way.

But... it is tempting to just do it the way @ozczecho has - as long as I can read the existing temp sensors via this + the custom component for home assistant , as I don't want to buy more :)

**Comment by ozczecho** [comment]
@L0rdCha0s & @tidalvirus - I just added a new endpoint `POST aircons/{selectedId}/zones/{zoneId}/temperature/{incDec}` that allows you to set the desired temperature for a zone. 

The home assistant custom control has not been updated (yet) to take advantage of this endpoint.

**Comment by L0rdCha0s** [comment]
Ahh - very nice! I'll have a quick read of the code now.  I have a homebridge plugin that is almost ready to publish, will send a link soon.

**Comment by Grubs** [comment]
@L0rdCha0s where can I find the HomeBridge plug-in?

**Comment by ozczecho** [comment]
Im closing this issue since zone based temperature control has been added

**Comment by Grubs** [comment]
@ozczecho how do I implement this feature in HA? I’m assuming I’ll end up with a thermostat per zone that has a temperature sensor installed?  I will be able the set the temp for that zone as well as switch it off/on? Would be nice to have sliders for the damper % on the zones without a temp sensor. I quite often adjust these at night to reduce the airflow and noise in the bedrooms without a temperature sensor

**Comment by ozczecho** [comment]
@Grubs - I implemented t his custom component: https://github.com/ozczecho/custom_components/tree/master/airtouch3

It may do a lot of the things you are after. My setup is described here: https://github.com/ozczecho/vzduch-dotek/issues/2#issuecomment-712127951
