### ISSUE TITLE
Airtouch 2 +

### ISSUE THREAD

**Issue by Selmaks** [ozczecho/vzduch-dotek#4]
Hi I was wondering if you would be willing to add support for the Airtouch 2 +?
https://www.polyaire.com.au/products/control-systems/airtouch-2-plus/

I have the API but it is a bit beyond me.

**Comment by ozczecho** [comment]
Hi @Selmaks - if you already have the api then you basically have what this project does - unless I have misunderstood you?

**Comment by Selmaks** [comment]
Hi @ozczecho  sorry when I said API I should of said AirTouch 2+ Communication Protocol. 

 I have the Communication Protocol however I am not sure on how to implement it. I was hoping to use domoticz to control it like you do for Home Assistant.

I was hoping you could look at the Airtouch 2 + Communication Protocol to see if it could be implemented into your project.
[AirTouch 2+ Communication Protocol V1.0.1.pdf](https://github.com/ozczecho/vzduch-dotek/files/5699201/AirTouch.2%2B.Communication.Protocol.V1.0.1.pdf)

**Comment by ozczecho** [comment]
Hi @Selmaks - I will check the similarity over the holidays, but your best bet is to reach out to others on forums like HA forum and see if you can find someone with AT 2+ panel who can help with the coding. Having the comms protocol is 1/2 the battle.

**Comment by Selmaks** [comment]
Hi @ozczecho . Np thanks for having a look.

 I was lucky enough I talked to the right person and they were willing to share the comms protocol.

**Comment by AndyMan17** [comment]
Hi just wondering if you would be willing to add support for the Airtouch 2. I just saw you did the new 2+. It would be amazing if you could help.

**Comment by ozczecho** [comment]
@AndyMan17 - I only implemented the AirTouch 3 Api, not the AirTouch 2+. For this type of work I would need to have access to AirTouch 2 system - which I dont have. 

I would check the various home automation forums - I would be surprised if no one has an Api available for AT2.
