### ISSUE TITLE
raspberry pi support (arm64)?

### ISSUE THREAD

**Issue by murf1** [ozczecho/vzduch-dotek#7]
Hey guys,

Excellent work on the API wrapper! I had a bit of trouble getting it running at first as I had port conflicts for :5353 with mDNS for homekit but I worked out where to change that and managed to get it working on my win10 laptop with HA running in docker on a pi 4. I'd love to get this container running on the pi also - any plans to support this architecture or tips on getting it running?

Cheers!

**Comment by ozczecho** [comment]
Hey @murf1,

I will fix the port being hard coded. It should be an option.

As for pi 4 - it should be possible. I think all you need to do is change https://github.com/ozczecho/vzduch-dotek/blob/master/VzduchDotek.Net.csproj and add the appropriate `RuntimeIdentifier` to `RuntimeIdentifiers`.

See https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids
