### ISSUE TITLE
Homebridge plugin

### ISSUE THREAD

**Issue by L0rdCha0s** [ozczecho/vzduch-dotek#9]
Hi there, 

Just a note (as some users have requested it) - I've now released a Homebridge (Homekit) plugin for your API, at: https://github.com/L0rdCha0s/homebridge-airtouch3-airconditioner

**Comment by ozczecho** [comment]
Awesome. I don't use homekit so I have not tried it. I have added a link to your implementation in the readme.  https://github.com/ozczecho/vzduch-dotek/blob/master/README.md#front-ends
